<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Projet Wall'Street</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        
        <link href="https://fonts.googleapis.com/css?family=Rock+Salt" rel="stylesheet"> 
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
        <link href="<?= $template !== 'home' ? '../public/css/normalize.css' : 'public/css/normalize.css' ?>"rel="stylesheet">
        <link href="<?= $template !== 'home' ? '../public/css/style.css' : 'public/css/style.css' ?> " rel="stylesheet" />
        
    </head>

    <body>
        <header>
        
            <nav>
                
            <a href="<?= $template !== 'home' ? '../index' : 'index' ?>.php">
                        <img src="<?= $template !== 'home' ? '../public/img/logol2.png' : 'public/img/logol2.png '?>" alt="Wall-Street"/>
            </a>
                    <div class="accueil">
                        <a class="accueil-style" href="<?= $template !== 'home' ? '../index' : 'index' ?>.php">Accueil</a>
                        <a class="accueil-style" href="<?= $template !== 'home' ? 'showWorksArt' : 'controllers/showWorksArt' ?>.php?">Liste des oeuvres</a>
                        <a class="accueil-style" href="<?= $template !== 'home' ? 'showArtist' : 'controllers/showArtist' ?>.php?">Liste des artistes</a>
                        <a class="accueil-style" href="../controllers/logout.php" >Logout</a>
                    </div>
                <
            </nav>

        </header>
            

        <main>
            <?php include 'templates/'. $template .'.phtml' ?>
        </main>

        <footer>
            <p>" Imaginez une ville où le graffiti ne serait pas illégal, une ville où tout le monde pourrait dessiner où il veut. Une ville où toutes les rues seraient couvertes de millions de couleurs et de petites expressions. Où attendre le bus ne serait jamais ennuyeux</p>
            <p>Imaginez une ville comme ça et arrêtez de vous appuyer sur le mur -&nbsp;peinture fraîche&nbsp;- "</p>
            <em><p>Site crée par <a href="mailto:audrey94300@hotmail.fr">Audrey Poul</a></p></em>
        </footer>
        
    </body>
</html>