<div id="add">

    <h1>Ajouter un artiste</h1>
    <form class="" action="../controllers/addArtist.php" method="post" enctype="multipart/form-data">
       
        <ul>

            <li>
                <label for="artiste"> Nom de l'Artiste :</label>
                <input type="text" id="nom" name="nom" >

            </li>

            <li>
                <label for="photo">Photo :</label>
                <input id="photo" name="photo" type="file">
                    
            </li>

            <li>
                <label class="textarea" for="contents">Description :</label>
                <textarea id="description" name="description" rows="20" cols="50"></textarea>
            </li>

            <li>
                <a href="showArtist.php">Annuler</a>
                <input class="bouton_add" type="submit" value="Enregistrer">
            </li>

        </ul>
            
    </form>
</div>

 



