<form class="" action="../controllers/addArtist.php" method="post" enctype="multipart/form-data">
    <fieldset>
        <legend>Créer un artiste</legend>
        <ul>
            <li>
                <label for="artiste"> Nom de l'Artiste :</label>
                <input type="text" id="artiste" name="nom">
                    
            </li>

            <li>
                <label for="photo">Photo :</label>
                <input id="photo" name="photo" type="file">
            </li>

            <li>
                <label class="textarea" for="contents">Description :</label>
                <textarea id="description" name="description" rows="50"></textarea>
            </li>

           <li>
                <label for="date">Date :</label>
                <input type="text" id="date" name="date">
            </li>

            <li>
                <a class="" href="">Annuler</a>
            
                <button class="" type="submit">Enregistrer</button>
                    
            </li>

            
        </ul>
        </fieldset>
</form>

