<form class="" action="../controllers/addWorksArt.php" method="post" enctype="multipart/form-data">
    <fieldset>
        <legend>Créer une oeuvre</legend>
        <ul>
            
            <li>
                <label for="titre">Titre de l'oeuvre :</label>
                <input type="text" id="title" name="titre">
            </li>
            
            
            

            <li>
                <label for="photo">Photo :</label>
                <input id="photo" name="photo" type="file">
                
            </li>

            <li>
                <label class="textarea" for="contents">Localisation :</label>
                <textarea id="localisation" name="localisation" rows="15"></textarea>
            </li>

            
           
            <li>
                
                <a class="" href="">Annuler</a>
                <input class="" type="submit" value="Enregistrer">
                
                
            </li>

        </ul>
    </fieldset>

</form> 

