<form class="" action="../controllers/addWorksArt.php" method="post" enctype="multipart/form-data">
    <fieldset>
        <legend>Créer une oeuvre</legend>
        <ul>
            
            <li>
                <label for="titre">Titre de l'oeuvre :</label>
                <input type="text" id="title" name="titre">
            </li>
            
            
            <li>
                <label for="artiste">Nom de l'artiste :</label>
                <select id="artiste" name="artiste">
                    <?php foreach($artistes as $artiste): ?>
                        <option value="<?= intval($artiste['id']) ?>"><?= htmlspecialchars($artiste['nom']) ?>) ?></option>
                    <?php endforeach ?>
                </select>
            </li>

            <li>
                <label for="photo">Photo :</label>
                <input id="photo" name="photo" type="file">
                
            </li>

            <li>
                <label class="textarea" for="contents">Localisation :</label>
                <textarea id="localisation" name="localisation" rows="15"></textarea>
            </li>

            <li>
                <label for="date">Date :</label>
                <input type="text" id="date" name="date">
            </li>
           
            <li>
                
                <a class="" href="">Annuler</a>
               
                <button class="" type="submit">Enregistrer</button>
                
            </li>

        </ul>
    </fieldset>

</form> 

