
<section>
    <h1>bla</h1>
    <article>
        <h2>
            <?= $artist['nom'] ?>
        </h2>
        <img src="<?= $pathToPic ?>/artist/<?= $artist['photo'] ?>" alt="<?= $artist['nom'] ?>">
        <p><?= $artist['description'] ?></p>
    </article>
</section>

<section>
    <h3>Les oeuvres</h3>
    <?php foreach($worksartResult as $worksart): ?>
        <a href="#">
            <img src="<?= $pathToPic ?>/worksart/<?= $worksart['photo'] ?>" alt="<?= $worksart['titre'] ?>">
        </a>
    <?php endforeach; ?>

    <button type="submit">Voir +</button>
</section>


