<div id="home">

    <section class="street-art">
        <h1>Le Street Art</h1>

        <article>
            <h2>Qu'est-ce que le Street Art&nbsp;? </h2>
            <figure id="slider" class="slider">
                <img src="" alt="Photo du slider">
                <div class="align-button">
                    
                    <a id="slider-previous" title="Image précédente "><i class="fas fa-angle-left"></i></a>
                    <figcaption></figcaption>
                  <a id="slider-next" title="Image suivante "><i class="fas fa-angle-right"></i></a>
                </div>
            </figure>
            
            <p>Le Street Art est un art développé sous une multitude de formes, dans des endroits publiques ou dans la rue. Le terme englobe la pratique du graffiti, du pochoir, de la projection vidéo, de la création d'affiche, du pastel sur rues et trottoirs...
            La valeur subversive du street art est très puissante et les motivations qui poussent les artistes à afficher leur art dans la rue sont des plus variées.<p> Parfois par activisme, parfois pour signifier un mécontentement face à un fait de société ou tout simplement pour passer un message percutant, le « street art » est un peu la tribune libre des artistes contemporains.
            Il s'agit d'un médium de communication très puissant qui vise un large public puisque facilement accessible et visible.</p> 
            <p>C'est est l'une des formes d'art la plus honnête, il n'y a ni élitisme ni battage publicitaire. Le Street Art s'expose sur les meilleurs murs qu'une ville puisse offrir et personne n'est dissuadé par le prix de l'entrée.
            Certains deviennent des "vandales" parce qu'ils veulent rendre le monde plus beau.</p> 
        </article>

    </section>

    <section class="artistes">
        <h3>Les artistes</h3>
        <div class="flex-artist">
            <?php foreach($artistResult as $artist): ?>
                
                    <div>        
                    
                        <h4><a href="/wall-street/controllers/artist.php?id=<?= $artist['id'] ?>"><?= $artist['nom'] ?></a></h4>
                        <a href="/wall-street/controllers/artist.php?id=<?= $artist['id'] ?>"><img src="public/img/artist/<?= $artist['photo'] ?>" alt="<?= $artist['nom'] ?>"></a>
                    
                    </div>
                
            <?php endforeach; ?>
        </div>
    </section>  

</div> 

