<div id="login">
    <h1>Bonjour Admin !</h1>
    <form action="../controllers/login.php" method="POST">
        <label for="email">Email : </label>
        <input placeholder="Email" type="text" id="email" name="email">
                
        <label for="pwd">Password : </label>
        <input placeholder="Password" type="password" id="pwd" name="pwd">
        <button class="" type="submit">Valider</button>       
    </form>
</div>