<div id="login">
    <h1>Bonjour Admin&nbsp;!</h1>
    <form action="../controllers/login.php" method="POST">
        <label for="email">Email : </label>
        <input type="text" id="email" name="email">
                
        <label for="password">Password : </label>
        <input  type="password" id="password" name="password">
        <button class="" type="submit">Valider</button>       
    </form>
</div>