<!-- <div id="my-modal" class="hide">
		<div class="commandes">
				
			<span class="close-modal">FERMER X</span>
        </div>

        
            <a href="#">
                <figure>
                    <img src="<?= $pathToPic ?>/worksart/<?= $worksart['photo'] ?>" alt="<?= $worksart['titre'] ?>">
                    <figcaption><?= $worksart['titre'] ?></figcaption>    
                </figure>
            </a>
            <p><?= $worksart['localisation'] ?></p>
       
			
			
    </div> -->
    



    <button id="myBtn">Open Modal</button>

<!-- The Modal -->
<div id="myModal" class="modal">

  <!-- Modal content -->
  <div class="modal-content">
    <span class="close">&times;</span>
    <p>Some text in the Modal..</p>
  </div>

</div>