<div id="showArtist">
    <table class="">
    <a href="addArtist.php">Ajouter un nouvel artiste</a>
    
        <thead>
            <tr>
                <th>Nom</th>
                <th>Photo</th>
                <th>Description</th>
                <th>Supprimer</th>
                    
            </tr>
        </thead>
        <tbody>
            <?php foreach($artistResult as $artist): ?>
                <tr>
                    <td class="shadow"><?=htmlspecialchars($artist['nom'])?></td>
                    <td ><img src="../public/img/artist/<?= $artist['photo'] ?>" alt="<?=$artist['nom']?>"></td>
                    <td class="description"><?=substr(htmlspecialchars($artist['description']), 0, 50)?></td>
                    
                    <td>
                    
                        <a href="deleteArtist.php?id=<?=intval($artist['id'])?>"><i class="fas fa-times"></i></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>    


        