<div id="showWorksArt">
    <table>
        <a href="addWorksArt.php">Ajouter une nouvelle oeuvre</a>
        <thead>
            <tr>
                <th>Titre de l'oeuvre</th>
                <th>Photo</th>
                <th>Localisation</th>
                <th>Supprimer</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($worksartResult as $worksart) : ?>
                <tr>
                    <td><a href="showWorksArt.php?id=<?=intval($worksart['id'])?>"><?=htmlspecialchars($worksart['titre'])?></a></td>
                    <td><img src="../public/img/worksart/<?= $worksart['photo'] ?>" alt="<?=$worksart['titre']?>"></td>
                    <td class="localisation"><?=htmlspecialchars($worksart['localisation'])?></td>
                    <td>
                        <a href="deleteWorksArt.php?id=<?=intval($worksart['id'])?>"><i class="fas fa-times"></i></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>